import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2d3133",
        "on-tertiary-fixed": "#001d31",
        "primary-fixed": "#dae2fd",
        "secondary-fixed": "#d3e4fe",
        "on-secondary-container": "#54647a",
        "on-tertiary-container": "#188ace",
        "on-primary": "#ffffff",
        "inverse-primary": "#bec6e0",
        "on-secondary-fixed": "#0b1c30",
        tertiary: "#000000",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "outline-variant": "#c6c6cd",
        "on-primary-container": "#7c839b",
        "on-surface-variant": "#45464d",
        background: "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "surface-tint": "#565e74",
        "tertiary-fixed-dim": "#93ccff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "on-background": "#191c1e",
        "secondary-container": "#d0e1fb",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#004b73",
        "on-surface": "#191c1e",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#38485d",
        "primary-container": "#131b2e",
        "surface-container-high": "#e6e8ea",
        "surface-container": "#eceef0",
        "error-container": "#ffdad6",
        surface: "#f7f9fb",
        "tertiary-container": "#001d31",
        outline: "#76777d",
        "surface-dim": "#d8dadc",
        primary: "#0F172A",
        "on-primary-fixed": "#131b2e",
        secondary: "#505f76",
        "secondary-fixed-dim": "#b7c8e1",
        "inverse-on-surface": "#eff1f3",
        "primary-fixed-dim": "#bec6e0",
        "surface-variant": "#e0e3e5",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#cce5ff",
      },
      fontFamily: {
        sans: ["Geist", "system-ui", "sans-serif"],
        mono: ["Geist Mono", "monospace"],
        "headline-lg": ["Geist"],
        "headline-md": ["Geist"],
        "headline-sm": ["Geist"],
        "body-lg": ["Geist"],
        "body-md": ["Geist"],
        "body-sm": ["Geist"],
        "label-md": ["Geist"],
        "label-sm": ["Geist"],
        "mono-data": ["Geist Mono"],
      },
      fontSize: {
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "mono-data": ["13px", { lineHeight: "20px", fontWeight: "400" }],
      },
      spacing: {
        base: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "sidebar-width": "260px",
        "sidebar-collapsed": "64px",
        "container-max": "1440px",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
